version: "3.8"

services:

  accounts:
    image: zhaoying1127/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eazybank-network

  loans:
    image: zhaoying1127/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eazybank-network

  cards:
    image: zhaoying1127/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eazybank-network

networks:
  eazybank-network: